import React, { useState } from 'react';
import './MetricInfo.scss';

/* Dictionary of every key financial metric with explanation + grading */
const METRICS = {
  pe_ratio: {
    title: 'P/E Ratio (Price-to-Earnings)',
    desc: 'Compares share price to annual earnings per share. Shows how much investors pay for ₹1 of earnings.',
    grades: [
      { range: 'Below 15', signal: 'up',      label: 'Value zone — potentially underpriced' },
      { range: '15 – 25',  signal: 'neutral',  label: 'Fair value for most sectors' },
      { range: '25 – 45',  signal: 'neutral',  label: 'Premium — growth expectations priced in' },
      { range: 'Above 45', signal: 'down',     label: 'Very high — vulnerable if growth disappoints' },
    ],
    tip: 'Compare to industry peers and the stock\'s own 5-year average for context.',
  },
  eps: {
    title: 'EPS — Earnings Per Share',
    desc: 'Net profit divided by total shares. Shows how much the company earns for each share you own.',
    grades: [
      { range: 'Positive & growing', signal: 'up',    label: 'Company is profitable and improving' },
      { range: 'Positive & flat',    signal: 'neutral', label: 'Profitable but growth has stalled' },
      { range: 'Negative',           signal: 'down',   label: 'Company is making a loss' },
    ],
    tip: 'Consistent EPS growth over 3–5 years is a strong quality signal.',
  },
  gross_margin: {
    title: 'Gross Margin',
    desc: 'Revenue minus cost of goods, as a % of revenue. Measures how efficiently the company produces its product.',
    grades: [
      { range: 'Above 50%', signal: 'up',     label: 'Exceptional pricing power (tech/pharma typical)' },
      { range: '25 – 50%',  signal: 'neutral', label: 'Healthy — most large-caps fall here' },
      { range: 'Below 15%', signal: 'down',   label: 'Thin margins — vulnerable to cost shocks' },
    ],
    tip: 'Software/pharma companies have high gross margins; commodity/retail have low ones.',
  },
  net_margin: {
    title: 'Net Profit Margin',
    desc: 'What % of every rupee of revenue the company keeps as profit after all expenses and taxes.',
    grades: [
      { range: 'Above 20%', signal: 'up',     label: 'Excellent profitability' },
      { range: '8 – 20%',   signal: 'neutral', label: 'Solid for most industries' },
      { range: 'Below 5%',  signal: 'down',   label: 'Very thin — small shocks can wipe profits' },
    ],
    tip: 'Net margin trend matters more than the absolute number.',
  },
  return_on_equity: {
    title: 'Return on Equity (ROE)',
    desc: 'How efficiently management generates profit from shareholders\' money. Net income ÷ Shareholders\' equity.',
    grades: [
      { range: 'Above 20%', signal: 'up',     label: 'Best-in-class capital efficiency' },
      { range: '12 – 20%',  signal: 'neutral', label: 'Acceptable — meets cost of equity' },
      { range: 'Below 8%',  signal: 'down',   label: 'Poor — destroying shareholder value' },
    ],
    tip: 'Warren Buffett screens for ROE > 15% consistently over 10 years.',
  },
  debt_to_equity: {
    title: 'Debt-to-Equity Ratio',
    desc: 'Total debt divided by shareholders\' equity. Shows how much the company relies on borrowed money.',
    grades: [
      { range: 'Below 0.5', signal: 'up',     label: 'Very low leverage — financial fortress' },
      { range: '0.5 – 1.5', signal: 'neutral', label: 'Manageable for most sectors' },
      { range: 'Above 2',   signal: 'down',   label: 'High leverage — risk increases during rate cycles' },
    ],
    tip: 'Banks/NBFCs naturally have higher D/E. Compare within the same sector.',
  },
  dividend_yield: {
    title: 'Dividend Yield',
    desc: 'Annual dividend per share as a % of the current share price. Income generated by holding the stock.',
    grades: [
      { range: 'Above 4%',  signal: 'up',     label: 'High income — but verify it\'s sustainable' },
      { range: '1 – 4%',    signal: 'neutral', label: 'Moderate income component' },
      { range: 'Below 1%',  signal: 'neutral', label: 'Growth-focused; reinvests profits' },
    ],
    tip: 'A very high yield sometimes signals the market expects a dividend cut.',
  },
  beta: {
    title: 'Beta (Market Sensitivity)',
    desc: 'Measures how much the stock moves relative to the broader market (Nifty 50). Beta = 1 means it moves with the index.',
    grades: [
      { range: 'Below 0.8', signal: 'up',     label: 'Defensive — less volatile than market' },
      { range: '0.8 – 1.2', signal: 'neutral', label: 'Market-correlated' },
      { range: 'Above 1.5', signal: 'down',   label: 'High volatility — amplifies both gains and losses' },
    ],
    tip: 'Low-beta stocks (utilities, FMCG) hold up better in bear markets.',
  },
  revenue_growth: {
    title: 'Revenue Growth (YoY)',
    desc: 'Year-over-year change in total revenue. Shows whether the business is expanding its top line.',
    grades: [
      { range: 'Above 15%', signal: 'up',     label: 'Strong growth — outpacing inflation meaningfully' },
      { range: '5 – 15%',   signal: 'neutral', label: 'Stable growth in line with GDP+ expectations' },
      { range: 'Below 0%',  signal: 'down',   label: 'Revenue contraction — requires investigation' },
    ],
    tip: 'Revenue growth with margin expansion is the most powerful combination.',
  },
  earnings_growth: {
    title: 'Earnings Growth (YoY)',
    desc: 'Year-over-year change in net profit/EPS. Drives long-term stock price appreciation.',
    grades: [
      { range: 'Above 20%', signal: 'up',     label: 'Compounding machine — supports premium valuation' },
      { range: '5 – 20%',   signal: 'neutral', label: 'Steady growth' },
      { range: 'Below 0%',  signal: 'down',   label: 'Earnings declining — P/E compression risk' },
    ],
    tip: 'Stocks with consistent 15%+ earnings growth over 5 years tend to be multi-baggers.',
  },
  price_to_book: {
    title: 'Price-to-Book (P/B)',
    desc: 'Share price divided by book value per share. Compares market value to the company\'s net assets.',
    grades: [
      { range: 'Below 1',   signal: 'up',     label: 'Trades below asset value — deep value' },
      { range: '1 – 3',     signal: 'neutral', label: 'Fair for asset-heavy businesses' },
      { range: 'Above 5',   signal: 'neutral', label: 'High — reflects intangibles/brand value' },
    ],
    tip: 'Most meaningful for banks and asset-heavy sectors like metals.',
  },
  mkt_cap: {
    title: 'Market Capitalisation',
    desc: 'Total market value of all outstanding shares. Determines the company\'s size category.',
    grades: [
      { range: 'Above ₹20,000 Cr', signal: 'up',     label: 'Large-cap — typically more stable and liquid' },
      { range: '₹5,000–₹20,000 Cr', signal: 'neutral', label: 'Mid-cap — growth potential with moderate risk' },
      { range: 'Below ₹5,000 Cr',  signal: 'neutral', label: 'Small-cap — higher risk, higher potential' },
    ],
    tip: 'Sebi classifies large-cap as top 100 stocks by full market cap.',
  },
  volume: {
    title: 'Trading Volume',
    desc: 'Number of shares traded today. High volume on a price move confirms conviction.',
    grades: [
      { range: 'Well above average', signal: 'up',     label: 'Strong institutional participation' },
      { range: 'Near average',        signal: 'neutral', label: 'Normal activity' },
      { range: 'Very low',            signal: 'down',   label: 'Low liquidity — large orders move price significantly' },
    ],
    tip: 'Price rise + rising volume = bullish confirmation. Price rise + falling volume = suspect move.',
  },
  week52_high: {
    title: '52-Week High',
    desc: 'The highest price the stock has traded at in the past year. Used as a technical resistance/breakout level.',
    grades: [
      { range: 'Trading at 52W high', signal: 'up',     label: 'Breakout momentum — bullish signal' },
      { range: '10–20% below high',   signal: 'neutral', label: 'Healthy consolidation zone' },
      { range: 'Over 40% below high', signal: 'down',   label: 'Significant underperformance vs prior peak' },
    ],
    tip: 'Stocks making new 52-week highs statistically continue higher over the next 3-6 months.',
  },
  week52_low: {
    title: '52-Week Low',
    desc: 'The lowest price in the past year. Used as technical support and a value reference.',
    grades: [
      { range: 'Near 52W low',           signal: 'down',   label: 'Potential distress or sector rotation out' },
      { range: '20–50% above low',       signal: 'neutral', label: 'Recovery underway' },
      { range: 'Well above 52W low',     signal: 'up',     label: 'Strong price recovery from lows' },
    ],
    tip: 'Stocks near 52-week lows often get value-buy interest from institutional investors.',
  },
};

const SIGNAL_COLORS = {
  up:      { bg: 'var(--up-dim)',   fg: 'var(--up)',   label: 'Positive' },
  neutral: { bg: 'var(--card3)',    fg: 'var(--text2)', label: 'Neutral' },
  down:    { bg: 'var(--down-dim)', fg: 'var(--down)', label: 'Caution' },
};

export default function MetricInfo({ metricKey, value, label, children, className = '' }) {
  const [open, setOpen] = useState(false);
  const info = METRICS[metricKey];

  return (
    <div className={`mi-wrap ${className}`}>
      <div
        className={`mi-row ${info ? 'mi-row--clickable' : ''} ${open ? 'mi-row--open' : ''}`}
        onClick={() => info && setOpen(o => !o)}
      >
        {children}
        {info && <span className="mi-chevron">{open ? '▲' : 'ℹ'}</span>}
      </div>

      {open && info && (
        <div className="mi-panel">
          <div className="mi-panel__title">{info.title}</div>
          <div className="mi-panel__desc">{info.desc}</div>

          <div className="mi-grades">
            {info.grades.map((g, i) => {
              const col = SIGNAL_COLORS[g.signal];
              return (
                <div key={i} className="mi-grade" style={{ background: col.bg }}>
                  <span className="mi-grade__range" style={{ color: col.fg }}>{g.range}</span>
                  <span className="mi-grade__label" style={{ color: col.fg }}>{g.label}</span>
                </div>
              );
            })}
          </div>

          {info.tip && (
            <div className="mi-panel__tip">
              <span>💡</span> {info.tip}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
